theme: jekyll-theme-minimal
title: Rafael's homepage
description: >
  Meu site pessoal criado com GitHub Pages e Jekyll, onde compartilho projetos, ideias e aprendizados em tecnologia.
author:
  name: Rafael Gomes da Silva
  email: rafaelgscc@gmail.com

minima:
  skin: solarized-dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

social_links:
    - title: Meu repositorio no GitHub
      icon: github
      url: "https://github.com/rafaelgscc"
    - title: Meu LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/rafael-gomes-da-silva-775b80123/"
