theme: minima
title: Blog do rafaelgscc
description: >
  Meu site pessoal criado com GitHub Pages e Jekyll, onde compartilho projetos, ideias e aprendizados em tecnologia.
author:
  name: Rafael Gomes da Silva
  email: rafaelgscc@gmail.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]  


#Os plugins ficam aqui
minima:
  skin: solarized-dark
  date_format: "%d %b, %Y"
  social_links:
    - title: Meu repositorio no GitHub
      icon: github
      url: "https://github.com/rafaelgscc"
    - title: Meu LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/rafael-gomes-da-silva-775b80123/"
  hide_site_feed_link: true
  #Tag para o primeiro paragrafo de posts
  show_excerpts: true